import numpy as np
import pandas as pd
from scipy.io import loadmat, savemat
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler
from scipy.stats import mode
import matplotlib.pyplot as plt

# 1. Reproducibility & Settings
np.random.seed(567)  # rng(567, 'twister')
feature_names = ['Spatial Clustering Entropy', 'Event Rate', 'CV of Inter-Arrival Times', 
                 'Pulse Width Variation', 'Spectral Centroid', 'Max Gas Gap']

# Load the partition generated by generate_partition.py
data = loadmat('newResultsCL.mat')
X = data['X']
y = data['y'].flatten()
groups = data['groups'].flatten()
idx_train = data['idxOuterTrain'].flatten().astype(bool)
idx_test = data['idxOuterTest'].flatten().astype(bool)

# Remove specific features [1, 4, 5] (MATLAB indices 1-based -> Python 0-based: 0, 3, 4)
features_to_remove = [0, 3, 4]
X = np.delete(X, features_to_remove, axis=1)
feature_names = [f for i, f in enumerate(feature_names) if i not in features_to_remove]

# --- 2. DATA SEGREGATION & "CLEAN TEST" FILTER ---
X_train_full = X[idx_train]
y_train_full = y[idx_train]
groups_train_full = groups[idx_train]

X_test_full = X[idx_test]
y_test_full = y[idx_test]
groups_test_full = groups[idx_test]

# Standardize: Train parameters applied to Test (zscore)
scaler = StandardScaler()
X_train_full = scaler.fit_transform(X_train_full)
X_test_full = scaler.transform(X_test_full)

# Identify the original 10 segments for each run (intraRunIdx < 10)
intra_run_idx = np.arange(len(X_test_full)) % 20
is_original = intra_run_idx < 10

# Clean Test Set (Original Only)
X_outer_test = X_test_full[is_original]
y_outer_test = y_test_full[is_original]
groups_outer_test = groups_test_full[is_original]

print(f"=== DATA PREPARED (RF) ===\nTraining set (Augmented): {len(X_train_full)} samples\nTesting set (Original Only): {len(X_outer_test)} samples")

# --- 3. HYPERPARAMETER TUNING (INNER CV) ---
num_trees_list = [50, 100, 200, 300]
num_folds_inner = 5
inner_f1_scores = []

# Group-based stratified split for inner CV to match MATLAB's unique ID partition
unique_train_groups, first_idx = np.unique(groups_train_full, return_index=True)
train_group_labels = y_train_full[first_idx]
skf = StratifiedKFold(n_splits=num_folds_inner)

print("\n=== STARTING INNER CV TO OPTIMIZE RF (numTrees) ===")
for n_trees in num_trees_list:
    fold_f1 = []
    for train_idx, val_idx in skf.split(unique_train_groups, train_group_labels):
        # Map unique IDs back to full augmented rows
        tr_ids, val_ids = unique_train_groups[train_idx], unique_train_groups[val_idx]
        idx_tr = np.isin(groups_train_full, tr_ids)
        idx_val = np.isin(groups_train_full, val_ids)
        
        # Train RF (MinLeafSize=1 is default in sklearn)
        model = RandomForestClassifier(n_estimators=n_trees, random_state=567)
        model.fit(X_train_full[idx_tr], y_train_full[idx_tr])
        
        y_pred_val = model.predict(X_train_full[idx_val])
        fold_f1.append(f1_score(y_train_full[idx_val], y_pred_val, average='macro'))
    
    mean_f1 = np.mean(fold_f1)
    inner_f1_scores.append(mean_f1)
    print(f"  numTrees = {n_trees} | Mean Inner Macro-F1: {mean_f1:.3f}")

# --- 4. FINAL MODEL TRAINING & EVALUATION ---
best_n_trees = num_trees_list[np.argmax(inner_f1_scores)]
model_final = RandomForestClassifier(n_estimators=best_n_trees, random_state=567)
model_final.fit(X_train_full, y_train_full)

y_pred_test = model_final.predict(X_outer_test)

print("\n=== FINAL RF PERFORMANCE (ORIGINAL TEST DATA ONLY) ===")
print(classification_report(y_outer_test, y_pred_test))
print(f"Best Hyperparameter (numTrees): {best_n_trees}")

# --- 5. MAJORITY VOTING (SYSTEM RELIABILITY) ---
unique_test_runs = np.unique(groups_outer_test)
run_data = []

for run_id in unique_test_runs:
    mask = (groups_outer_test == run_id)
    # Mode returns the most frequent value
    voted_regime = mode(y_pred_test[mask], keepdims=True).mode[0]
    freq = np.sum(y_pred_test[mask] == voted_regime)
    true_regime = y_outer_test[mask][0]
    confidence = (freq / 10) * 100
    run_data.append([run_id, true_regime, voted_regime, confidence])

run_results = pd.DataFrame(run_data, columns=['RunID', 'TrueRegime', 'VotedRegime', 'Confidence'])

# Balanced Accuracy
sensitivity = []
for c in np.unique(run_results['TrueRegime']):
    subset = run_results[run_results['TrueRegime'] == c]
    sensitivity.append(np.mean(subset['TrueRegime'] == subset['VotedRegime']))

print(f"\nStandard Run-Level Accuracy: {np.mean(run_results['TrueRegime'] == run_results['VotedRegime'])*100:.2f}%")
print(f"Balanced Run-Level Accuracy: {np.mean(sensitivity)*100:.2f}%")

# --- 6. PERMUTATION IMPORTANCE ---
print("\nComputing RF Permutation Importance (30 repeats)...")
num_repeats = 30
baseline_error = 1 - model_final.score(X_outer_test, y_outer_test)
importance_results = np.zeros((num_repeats, X_outer_test.shape[1]))

for r in range(num_repeats):
    for i in range(X_outer_test.shape[1]):
        X_p = X_outer_test.copy()
        np.random.shuffle(X_p[:, i])
        perm_error = 1 - model_final.score(X_p, y_outer_test)
        importance_results[r, i] = perm_error - baseline_error

# Plotting
plt.figure(figsize=(10, 6))
plt.boxplot(importance_results, vert=False, labels=feature_names)
plt.axvline(0, color='r', linestyle='--')
plt.title("RF Feature Importance (Increase in Misclassification Rate)")
plt.xlabel("Increase in Error")
plt.gca().invert_yaxis()
plt.show()

# 7. SAVE RESULTS
savemat('rf_final_results_clean.mat', {'best_numTrees': best_n_trees, 'runResults': run_results.to_dict('list')})
